c------------------------------------------------------------------------------c
c This file contains the needed information about all the DM particles.
c------------------------------------------------------------------------------c
      mdm(1) = abs(Mneu1)
      dof_dm(1) = 2.0
      dm_sm_scattering(1) = .false.
      dm_names(1) = 'n1'
      dm_index(1) = 2
      dm_antinames(1) = 'n1'
      dm_antiindex(1) = 2
c------------------------------------------------------------------------------c
