      SUBROUTINE SMATRIX_N1N1_H1H1(P,ANS)
C     
C     Generated by MadGraph 5 v. 1.5.12, 2013-08-21
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     MadGraph StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: n1 n1 > h1 h1 WEIGHTED=4
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=4)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 MATRIX_N1N1_H1H1
      INTEGER IHEL,IDEN, I
      INTEGER JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB)
      DATA NTRY/0/
      DATA GOODHEL/NCOMB*.FALSE./
      DATA (NHEL(I,   1),I=1,4) /-1,-1, 0, 0/
      DATA (NHEL(I,   2),I=1,4) /-1, 1, 0, 0/
      DATA (NHEL(I,   3),I=1,4) / 1,-1, 0, 0/
      DATA (NHEL(I,   4),I=1,4) / 1, 1, 0, 0/
      DATA IDEN/ 8/
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      ANS = 0D0
      DO IHEL=1,NCOMB
        IF (GOODHEL(IHEL) .OR. NTRY .LT. 100) THEN
          T=MATRIX_N1N1_H1H1(P ,NHEL(1,IHEL),JC(1))
          ANS=ANS+T
          IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL)) THEN
            GOODHEL(IHEL)=.TRUE.
          ENDIF
        ENDIF
      ENDDO
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION MATRIX_N1N1_H1H1(P,NHEL,IC)
C     
C     Generated by MadGraph 5 v. 1.5.12, 2013-08-21
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: n1 n1 > h1 h1 WEIGHTED=4
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=10)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=14, NCOLOR=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(18,NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM(1)/1/
      DATA (CF(I,1),I=1,1) /1/
C     ----------
C     BEGIN CODE
C     ----------
      CALL OXXXXX(P(0,1),MNEU1,NHEL(1),-1*IC(1),W(1,1))
      CALL IXXXXX(P(0,2),MNEU1,NHEL(2),+1*IC(2),W(1,2))
      CALL SXXXXX(P(0,3),+1*IC(3),W(1,3))
      CALL SXXXXX(P(0,4),+1*IC(4),W(1,4))
      CALL FFS1_2_3(W(1,2),W(1,1),GC_808,GC_808,MH01,WH01,W(1,5))
C     Amplitude(s) for diagram number 1
      CALL SSS1_0(W(1,3),W(1,4),W(1,5),GC_839,AMP(1))
      CALL FFS1_2_3(W(1,2),W(1,1),GC_809,GC_809,MH02,WH02,W(1,5))
C     Amplitude(s) for diagram number 2
      CALL SSS1_0(W(1,3),W(1,4),W(1,5),GC_840,AMP(2))
      CALL FFS1_2_1(W(1,1),W(1,3),GC_808,GC_808,MNEU1,ZERO,W(1,5))
C     Amplitude(s) for diagram number 3
      CALL FFS1_2_0(W(1,2),W(1,5),W(1,4),GC_808,GC_808,AMP(3))
      CALL FFS1_2_1(W(1,1),W(1,3),GC_810,GC_728,MNEU2,WNEU2,W(1,5))
C     Amplitude(s) for diagram number 4
      CALL FFS1_2C1_0(W(1,2),W(1,5),W(1,4),GC_810,GC_728,AMP(4))
      CALL FFS1_2_1(W(1,1),W(1,3),GC_814,GC_732,MNEU3,WNEU3,W(1,5))
C     Amplitude(s) for diagram number 5
      CALL FFS1_2C1_0(W(1,2),W(1,5),W(1,4),GC_814,GC_732,AMP(5))
      CALL FFS1_2_1(W(1,1),W(1,3),GC_738,GC_738,MNEU4,WNEU4,W(1,5))
C     Amplitude(s) for diagram number 6
      CALL FFS1_2C1_0(W(1,2),W(1,5),W(1,4),GC_738,GC_738,AMP(6))
      CALL FFS1_2_1(W(1,1),W(1,4),GC_808,GC_808,MNEU1,ZERO,W(1,5))
C     Amplitude(s) for diagram number 7
      CALL FFS1_2_0(W(1,2),W(1,5),W(1,3),GC_808,GC_808,AMP(7))
      CALL FFS1_2_1(W(1,1),W(1,4),GC_810,GC_728,MNEU2,WNEU2,W(1,5))
C     Amplitude(s) for diagram number 8
      CALL FFS1_2C1_0(W(1,2),W(1,5),W(1,3),GC_810,GC_728,AMP(8))
      CALL FFS1_2_1(W(1,1),W(1,4),GC_814,GC_732,MNEU3,WNEU3,W(1,5))
C     Amplitude(s) for diagram number 9
      CALL FFS1_2C1_0(W(1,2),W(1,5),W(1,3),GC_814,GC_732,AMP(9))
      CALL FFS1_2_1(W(1,1),W(1,4),GC_738,GC_738,MNEU4,WNEU4,W(1,5))
C     Amplitude(s) for diagram number 10
      CALL FFS1_2C1_0(W(1,2),W(1,5),W(1,3),GC_738,GC_738,AMP(10))
      JAMP(1)=-AMP(1)-AMP(2)-AMP(3)-AMP(4)-AMP(5)-AMP(6)-AMP(7)-AMP(8)
     $ -AMP(9)-AMP(10)

      MATRIX_N1N1_H1H1 = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        MATRIX_N1N1_H1H1 = MATRIX_N1N1_H1H1+ZTEMP*DCONJG(JAMP(I))
     $   /DENOM(I)
      ENDDO
      END
