c-------------------------------------------------------------------------c
      subroutine getfsmasses_ann(pmass, i, j, k)
c-------------------------------------------------------------------------c
c                                                                         c
c  This subroutine which is dynamically generated by the MadDM python     c
c  codes reads through the pmass.inc files to get the external particle   c
c  masses for the annihilation processes.                                 c
c                                                                         c
c-------------------------------------------------------------------------c
      implicit none
      include 'maddm.inc'
      include 'coupl.inc'
      
c input parameters
      integer i, j, k

      if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.1)) then
        include 'pmass_n1n1_uux.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.2)) then
        include 'pmass_n1n1_ddx.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.3)) then
        include 'pmass_n1n1_vevex.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.4)) then
        include 'pmass_n1n1_vtvtx.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.5)) then
        include 'pmass_n1n1_emep.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.6)) then
        include 'pmass_n1n1_ttx.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.7)) then
        include 'pmass_n1n1_bbx.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.8)) then
        include 'pmass_n1n1_zz.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.9)) then
        include 'pmass_n1n1_zh1.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.10)) then
        include 'pmass_n1n1_wpwm.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.11)) then
        include 'pmass_n1n1_h1h1.inc' 
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.12)) then
        include 'pmass_n1n1_tamtap.inc' 
      endif

      return
      end



c-------------------------------------------------------------------------c
      subroutine getfsmasses_dm2dm(pmass, i, j, k)
c-------------------------------------------------------------------------c
c                                                                         c
c  This subroutine which is dynamically generated by the MadDM python     c
c  codes reads through the pmass.inc files to get the external particle   c
c  masses for the DM -> DM processes.                                     c
c                                                                         c
c-------------------------------------------------------------------------c
      implicit none
      include 'maddm.inc'
      include 'coupl.inc'
      
c input parameters
      integer i, j, k



      return
      end



c-------------------------------------------------------------------------c
      subroutine getfsmasses_scattering(pmass, i, j, k)
c-------------------------------------------------------------------------c
c                                                                         c
c  This subroutine which is dynamically generated by the MadDM python     c
c  codes reads through the pmass.inc files to get the external particle   c
c  masses for the DM/SM scattering processes.                             c
c                                                                         c
c-------------------------------------------------------------------------c
      implicit none
      include 'maddm.inc'
      include 'coupl.inc'
      
c input parameters
      integer i, j, k



      return
      end




c-------------------------------------------------------------------------c
      function smatrix_ann(p_ext, i, j, k)
c-------------------------------------------------------------------------c
c                                                                         c
c  This subroutine is generated dynamically by MadDM python scripts that  c
c  are set up to call the individual matrix element subroutines as they   c
c  are generated by MadGraph.                                             c
c                                                                         c
c  This function returns the smatrix value for an individual              c
c  annihlation process.                                                   c
c                                                                         c
c-------------------------------------------------------------------------c
      implicit none
      include 'maddm.inc'
      include 'coupl.inc'

c input parameters
      double precision p_ext(0:3,4)
      integer i, j, k

      if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.1)) then
        call smatrix_n1n1_uux(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.2)) then
        call smatrix_n1n1_ddx(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.3)) then
        call smatrix_n1n1_vevex(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.4)) then
        call smatrix_n1n1_vtvtx(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.5)) then
        call smatrix_n1n1_emep(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.6)) then
        call smatrix_n1n1_ttx(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.7)) then
        call smatrix_n1n1_bbx(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.8)) then
        call smatrix_n1n1_zz(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.9)) then
        call smatrix_n1n1_zh1(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.10)) then
        call smatrix_n1n1_wpwm(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.11)) then
        call smatrix_n1n1_h1h1(p_ext,smatrix_ann)
      else if ((i.eq.1) .and. (j.eq.1) .and. (k.eq.12)) then
        call smatrix_n1n1_tamtap(p_ext,smatrix_ann)
      endif

      return
      end



c-------------------------------------------------------------------------c
      function smatrix_dm2dm(p_ext, i, j, k)
c-------------------------------------------------------------------------c
c                                                                         c
c  This subroutine is generated dynamically by MadDM python scripts that  c
c  are set up to call the individual matrix element subroutines as they   c
c  are generated by MadGraph.                                             c
c                                                                         c
c  This function returns the smatrix value for an idividual DM -> DM      c
c  process.                                                               c
c                                                                         c
c-------------------------------------------------------------------------c
      implicit none
      include 'maddm.inc'
      include 'coupl.inc'

c input parameters
      double precision p_ext(0:3,4)
      integer i, j, k



      return
      end



c-------------------------------------------------------------------------c
      function smatrix_scattering(p_ext, i, j, k)
c-------------------------------------------------------------------------c
c                                                                         c
c  This subroutine is generated dynamically by MadDM python scripts that  c
c  are set up to call the individual matrix element subroutines as they   c
c  are generated by MadGraph.                                             c
c                                                                         c
c  This function returns the smatrix value for an indiviudual DM/SM       c
c  scattering process.                                                    c
c                                                                         c
c-------------------------------------------------------------------------c
      implicit none
      include 'maddm.inc'
      include 'coupl.inc'

c input parameters
      double precision p_ext(0:3,4)
      integer i, j, k



      return
      end